version: '2'
services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy:1.6.3
    container_name: nginx-proxy
    restart: "always"
    environment:
      - NO_COLOR=1
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ${PWD}/config/certs:/etc/nginx/certs
    ports:
      - 443:443
      - 80:80
    networks:
      - prometheus

  prometheus: 
    image: quay.io/prometheus/prometheus:v2.55.0 
    container_name: prometheus
    restart: "always"
    environment:
      - ARG_COMMAND=/bin/prometheus
      - ARG_PREFIX=PROM_
      - PROM_WEB_EXTERNAL__URL=${EXTERNAL_SCHEME:-https}://${EXTERNAL_NAME}/prometheus
      - PROM_CONFIG_FILE=/etc/config/prometheus.yml
      - PROM_STORAGE_TSDB_PATH=/data
      - PROM_WEB_CONSOLE_LIBRARIES=/etc/prometheus/console_libraries
      - PROM_WEB_CONSOLE_TEMPLATES=/etc/prometheus/consoles
      - PROM_STORAGE_TSDB_RETENTION_TIME=10d
      - VIRTUAL_HOST=${EXTERNAL_NAME}
      - VIRTUAL_PATH=/prometheus
      - VIRTUAL_PORT=9090
    volumes:
      - ${PWD}/config/entrypoint.sh:/tmp/entrypoint.sh
      - ${PWD}/config/prometheus.yml:/etc/config/prometheus.yml
      - ${PWD}/config/rules/:/etc/config/rules/
      - ${PWD}/config/alerts/:/etc/config/alerts/
      - ${PROMETHEUSDATA}:/data
    entrypoint: ["/bin/sh", "-c", "/tmp/entrypoint.sh"]
    extra_hosts:
      - "tools-vm:192.168.2.115"
    networks:
      - prometheus

  alertmanager:
    image: quay.io/prometheus/alertmanager:v0.27.0
    container_name: alertmanager
    restart: "always"
    environment:
      - ARG_COMMAND=/bin/alertmanager
      - ARG_PREFIX=PROM_
      - PROM_WEB_EXTERNAL__URL=${EXTERNAL_SCHEME:-https}://${EXTERNAL_NAME}/alertmanager
      - PROM_CONFIG_FILE=/etc/alertmanager/alertmanager.yml
      - PROM_STORAGE_PATH=/alertmanager
      - VIRTUAL_HOST=${EXTERNAL_NAME}
      - VIRTUAL_PATH=/alertmanager
      - VIRTUAL_PORT=9093
    entrypoint: ["/bin/sh", "-c", "/tmp/entrypoint.sh"]
    volumes:
      - ${PWD}/config/entrypoint.sh:/tmp/entrypoint.sh
      - ${PWD}/config/alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
      - ${ALERTMANAGERDATA}:/alertmanager
    networks:
      - prometheus

  node-exporter:
    image: quay.io/prometheus/node-exporter:v1.8.2
    container_name: node-exporter
    restart: "always"
    environment: {}
    network_mode: host
    pid: host
    cap_add:
      - SYS_TIME
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/host'
      - '--path.udev.data=/host/root/run/udev/data'
      - '--collector.filesystem.mount-points-exclude=^/(dev|proc|sys|var/lib/docker/.+)($|/)'
      - '--collector.filesystem.fs-types-exclude=^(autofs|binfmt_misc|bpf|cgroup2?|configfs|debugfs|devpts|devtmpfs|fusectl|hugetlbfs|iso9660|mqueue|nsfs|overlay|proc|procfs|pstore|rpc_pipefs|securityfs|selinuxfs|squashfs|sysfs|tracefs)$'
    volumes:
      - '/:/host:ro,rslave'

networks:
  prometheus:
