global: {}
route:
  group_by: ['alertname','severity']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  receiver: 'null'
  routes:
    - match:
        severity: 'critical'
      receiver: 'web.hook' 
receivers:
  - name: 'web.hook'
    webhook_configs:
      - url: 'http://127.0.0.1:5001/'
    matchers:
      - severity =~ "warning|error|critical"
  - name: 'null'
    matchers:
      - alertname =~ "InfoInhibitor|Watchdog"
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
  - source_matchers:
      - 'severity = critical'
    target_matchers:
      - 'severity =~ warning|info'
    equal:
      - 'alertname'
  - source_matchers:
      - 'severity = warning'
    target_matchers:
      - 'severity = info'
    equal:
      - 'alertname'
  - source_matchers:
      - 'alertname = InfoInhibitor|Watchdog'
    target_matchers:
      - 'severity = info'
