global:
  evaluation_interval: 1m
  scrape_interval: 30s
  scrape_timeout: 10s
rule_files:
  - /etc/config/rules/*.yaml
  - /etc/config/alerts/*.yaml
alerting:
  alertmanagers:
    - static_configs:
      - targets:
        - alertmanager:9093
      path_prefix: "alertmanager/"
scrape_configs:
  - job_name: prometheus
    file_sd_configs:
      - files:
          - 'prometheus.json'

  - job_name: alertmanager
    file_sd_configs:
      - files:
          - 'alertmanager.json'

  - job_name: node-exporter
    scrape_interval: 30s
    scrape_timeout: 10s
    file_sd_configs:
      - files:
          - 'node-exporter.json'
        refresh_interval: 1m
    relabel_configs:
      - source_labels: [__address__]
        regex: '(.*):9100'
        replacement: ${1}
        action: replace
        target_label: nodename
  
  - job_name: data-prepper
    scrape_interval: 30s
    scrape_timeout: 10s
    file_sd_configs:
      - files:
          - 'data-prepper.json'
    basic_auth:
      username: 'prepper'
      password: 'prepper'
  
  - job_name: docker 
    scrape_interval: 30s
    scrape_timeout: 10s
    file_sd_configs:
      - files:
          - 'docker-exporter.json'
        refresh_interval: 1m
    relabel_configs:
      - source_labels: [__address__]
        regex: '(.*):9323'
        replacement: ${1}
        action: replace
        target_label: nodename
  
  - job_name: kafka
    scrape_interval: 30s
    scrape_timeout: 10s
    file_sd_configs:
      - files:
          - 'kafka-exporter.json'
        refresh_interval: 1m
    relabel_configs:
      - source_labels: [__address__]
        regex: '(.*):(9308|9999)'
        replacement: ${1}
        action: replace
        target_label: nodename
