global:
  evaluation_interval: 1m
  scrape_interval: 1m
  scrape_timeout: 10s
rule_files:
  - /etc/config/rules/*.yaml
  - /etc/config/alerts/*.yaml
alerting:
  alertmanagers:
    - static_configs:
      - targets:
        - alertmanager:9093
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
        - localhost:9090
        labels:
          cluster: talos-cluster
  - job_name: alertmanager
    static_configs:
      - targets:
        - alertmanager:9093
        labels:
          cluster: talos-cluster

  - job_name: node-exporter
    scrape_interval: 30s
    scrape_timeout: 10s
    static_configs:
      - targets:
        - tools-vm:9100
        labels:
          cluster: talos-cluster
    relabel_configs:
      - source_labels: [__address__]
        regex: '(.*):9100'
        replacement: ${1}
        action: replace
        target_label: nodename
